theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: false
  logo:
    header: "/assets/images/mouvess.png"
    footer: "/assets/images/mouvess-complet.png"
  breadcrumb:
    position: after-hero
  posts:
    index:
      truncate_description: 0
      layout: grid # grid | list