[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/adherents/noesya/index.html"
to = "/organisations/noesya/"

[[redirects]]
from = "/equipe/index.html"
to = "/personnes/"

[[redirects]]
from = "/notre-plaidoyer/index.html"
to = "/plaidoyer/"

[[redirects]]
from = "/qui-sommes-nous/adherents/noesya/index.html"
to = "/organisations/noesya/"

[[redirects]]
from = "/actualites/agenda/archives/index.html"
to = "/agenda/archives/"

[[redirects]]
from = "/qui-sommes-nous-1/equipe/equipe-editoriale/index.html"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/actualites/expositions/archives-expositions/index.html"
to = "/expositions/archives-expositions/"

[[redirects]]
from = "/qui-sommes-nous-1/equipe/index.html"
to = "/personnes/"

[[redirects]]
from = "/jobtiens-lagrement-esus/lagrement-esus/index.html"
to = "/lagrement-esus/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/qui-sommes-nous/organisations/noesya/index.html"
to = "/organisations/noesya/"

[[redirects]]
from = "/actualites/agenda/index.html"
to = "/agenda/"

[[redirects]]
from = "/qui-sommes-nous-1/equipe/jonathan-jeremiasz/index.html"
to = "/personnes/jonathan-jeremiasz/"

[[redirects]]
from = "/lassociation/adherents/noesya/index.html"
to = "/organisations/noesya/"

[[redirects]]
from = "/equipe/jonathan-jeremiasz/index.html"
to = "/personnes/jonathan-jeremiasz/"

[[redirects]]
from = "/agenda/2026/esus-tour-etape-ile-de-france/index.html"
to = "/agenda/2026/toulouse-2026/"

[[redirects]]
from = "/actualites/expositions/index.html"
to = "/expositions/"

[[redirects]]
from = "/jobtiens-lagrement-esus/tout-savoir-sur-lagrement-esus/index.html"
to = "/lagrement-esus/"

[[redirects]]
from = "/qui-sommes-nous/organisations/index.html"
to = "/organisations/"

