[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/adherents/noesya/index.html"
to = "/qui-sommes-nous/adherents/noesya/"

[[redirects]]
from = "/equipe/index.html"
to = "/qui-sommes-nous-1/equipe/"

[[redirects]]
from = "/actualites/agenda/archives/index.html"
to = "/agenda/archives/"

[[redirects]]
from = "/equipe/jonathan-jeremiasz/index.html"
to = "/qui-sommes-nous-1/equipe/jonathan-jeremiasz/"

[[redirects]]
from = "/actualites/expositions/archives-expositions/index.html"
to = "/expositions/archives-expositions/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/qui-sommes-nous-1/equipe/equipe-editoriale/"

[[redirects]]
from = "/actualites/agenda/index.html"
to = "/agenda/"

[[redirects]]
from = "/lassociation/adherents/noesya/index.html"
to = "/qui-sommes-nous/adherents/noesya/"

[[redirects]]
from = "/actualites/expositions/index.html"
to = "/expositions/"

