[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/lassociation/statuts/index.html"
to = "/qui-sommes-nous/statuts/"

[[redirects]]
from = "/adherents/noesya/index.html"
to = "/qui-sommes-nous/adherents/noesya/"

[[redirects]]
from = "/adherents/index.html"
to = "/qui-sommes-nous/adherents/"

[[redirects]]
from = "/organisations/index.html"
to = "/qui-sommes-nous/adherents/"

[[redirects]]
from = "/lassociation/adherents/index.html"
to = "/qui-sommes-nous/adherents/"

[[redirects]]
from = "/lassociation/gouvernance/index.html"
to = "/qui-sommes-nous/gouvernance/"

[[redirects]]
from = "/lassociation/adherents/noesya/index.html"
to = "/qui-sommes-nous/adherents/noesya/"

[[redirects]]
from = "/lassociation/index.html"
to = "/qui-sommes-nous/"

[[redirects]]
from = "/lassociation/manifeste-fondateur/index.html"
to = "/qui-sommes-nous/manifeste-fondateur/"

